### ISSUE TITLE
Have some sort of 'template' concept.

### ISSUE THREAD

**Issue by gabesullice** [prestonso/hydrant#4]
Wish List Item: I'd love to see some transformation happen between the object returned directly from Drupal and something that's more relevant and familiar on the front end.

The code might look something like this:

``` javascript
hydrant.setModel('user', {
  template: {
    id: "object.uid.target_id"
    firstName: "object.field_first_name.value"
  }
});
```

Now, whenever we fetch users from the back end, I imagine we'll just be given a nice clean object like:

``` json
{
  "id": 134,
  "firstName": "Sally"
}
```

**Comment by mattgrill** [comment]
@gabesullice Have you see this? https://www.npmjs.com/package/json-mapper

**Comment by mattgrill** [comment]
@gabesullice We've moved this project to an official Acquia repository, https://github.com/acquia/hydrant/issues. I'll close this issue, but if you'd like to reopen it on the official Acquia repo that would be great.
